### ISSUE TITLE
AttributeError in on_conn_checkin() (dbapi_connection can be None)

### ISSUE THREAD

**Issue by gward** [level12/pals#20]
We just did a bit of maintenance on our PostgreSQL server. (It's actually an AWS RDS PostgreSQL, but I don't think that matters.)

This resulted in the following error:
```
[2020-03-02 16:01:38,519 E 14 fn.flasknoir.errorhandlers] POST /heartbeat?: internal error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.AdminShutdown: terminating connection due to administrator command
SSL connection has been closed unexpectedly


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.errors.AdminShutdown) terminating connection due to administrator command
SSL connection has been closed unexpectedly
```
Nothing surprising there, and nothing to do with pals. Just giving some context.

Then it turns out that pals' `on_conn_checkin()` method blew up while unwinding the stack from that exception:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  [...my application code...]
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1487, in _handle_dbapi_exception
    self.engine.pool._invalidate(dbapi_conn_wrapper, e)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 325, in _invalidate
    connection.invalidate(exception)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 956, in invalidate
    self._checkin()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 847, in _checkin
    fairy=self,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    connection_record.checkin()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 527, in checkin
    pool.dispatch.checkin(connection, self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/pals/core.py", line 45, in on_conn_checkin
    with dbapi_connection.cursor() as cur:
AttributeError: 'NoneType' object has no attribute 'cursor'
```

Conclusion: it is possible for SQLalchemy to pass None as `dbapi_connection`. pals should defend against this -- probably by doing nothing!

Very minor bug: this request still would have failed with a 500 error.

**Comment by rsyring** [comment]
I think this was handled by: https://github.com/level12/pals/pull/26/files

Feel free to re-open if that isn't the case.
